## PyTorch Basics

    Tensors: Core data structure, similar to NumPy arrays but with GPU support.

    Autograd: Automatic differentiation for backpropagation.

    nn.Module: Base class for building neural networks.

    Optimizers: Algorithms like SGD or Adam to update weights.

    DataLoader: Efficiently loads and batches datasets.

    Apple Silicon Macs don’t support NVIDIA CUDA, but PyTorch has a backend called MPS (Metal Performance Shaders).

In [1]:
import torch

In [2]:
#MPS available
torch.backends.mps.is_available()

True

In [3]:
#Check Apple Silicon GPU support
torch.backends.mps.is_built()

True

In [4]:
# Check CUDA GPU availability.
torch.cuda.is_available()

False

In [5]:
#force PyTorch to use the GPU

device = torch.device("mps")  # for Apple Silicon
x = torch.rand(1000, 1000, device=device)
y = torch.rand(1000, 1000, device=device)
z = torch.matmul(x, y)
print(z)


tensor([[254.7269, 240.5233, 244.1742,  ..., 241.5219, 251.4563, 240.6390],
        [245.7762, 244.2520, 241.2968,  ..., 240.0065, 248.6869, 234.7482],
        [252.5898, 241.5654, 243.3484,  ..., 237.5735, 251.2589, 242.2695],
        ...,
        [253.5563, 245.9942, 246.1090,  ..., 243.6895, 256.1215, 245.8695],
        [250.3257, 250.2436, 244.9783,  ..., 240.7114, 256.1317, 242.4181],
        [247.1677, 239.7889, 243.0845,  ..., 237.4298, 247.6942, 240.0444]],
       device='mps:0')


In [6]:
torch.__version__

'2.8.0'

In [7]:
# Create a tensor
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [8]:
#Create zero tensor.
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#Create ones tensor
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
#Random tensor
torch.rand(4,4)

tensor([[0.2056, 0.5288, 0.0038, 0.1741],
        [0.1535, 0.0031, 0.8956, 0.6895],
        [0.8773, 0.5956, 0.5154, 0.2042],
        [0.6104, 0.2377, 0.6300, 0.7142]])

In [11]:
#Random Integers
torch.floor(torch.rand(4,4)*10).int()

tensor([[8, 6, 7, 1],
        [1, 7, 7, 5],
        [5, 9, 6, 9],
        [7, 8, 4, 8]], dtype=torch.int32)

In [12]:
#Random Integers using randint
torch.randint(3,50,size=(4,4))

tensor([[45,  4,  4, 28],
        [42, 46, 15, 10],
        [36, 11, 44, 23],
        [16, 47, 45, 39]])

In [13]:
#Sequential Integers
torch.arange(25).reshape(5,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [14]:
x =torch.randint(4,40,size=(5,5))
x

tensor([[31, 11, 31, 11, 28],
        [10, 11, 11, 19, 17],
        [22, 28, 36, 21, 20],
        [12, 38,  5,  8,  4],
        [23, 27, 36, 39, 10]])

In [15]:
#Get tensor shape
x.shape

torch.Size([5, 5])

In [16]:
#Move tensor to GPU
x.to("mps")

tensor([[31, 11, 31, 11, 28],
        [10, 11, 11, 19, 17],
        [22, 28, 36, 21, 20],
        [12, 38,  5,  8,  4],
        [23, 27, 36, 39, 10]], device='mps:0')

## Dot Product

    The dot product is defined for two vectors (1D tensors).

    It multiplies corresponding elements and sums them up.

In [17]:
u = torch.tensor([1, 2, 3])
v = torch.tensor([4, 5, 6])

dot = torch.dot(u, v)
print(dot)   # 1*4 + 2*5 + 3*6 = 32

tensor(32)


## Matrix Multiplication (torch.matmul)

    Works for 2D tensors (matrices) or higher dimensions.

    It’s a generalization of the dot product: each element in the result is a dot product between a row of the first matrix and a column of the second.
    
    If you have two tensors with shapes,(A:m×n)and(B:n×p)then: torch.matmul(A,B)⇒(m×p) and, inner dimensions (n) must match.

In [18]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[2, 0], [1, 2]])

result = torch.matmul(a, b)
print(f"a \n {a}")
print(f"b \n {b}")
print(f"matmul \n {result}")


a 
 tensor([[1, 2],
        [3, 4]])
b 
 tensor([[2, 0],
        [1, 2]])
matmul 
 tensor([[ 4,  4],
        [10,  8]])
