In [1]:
import torch

# Create a 2D tensor (2 rows, 3 columns)
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("Original shape:", x.shape)   
print("Original tensor:\n", x)

# Use view(-1) to flatten into 1D
y = x.view(-1)

print("\nReshaped shape:", y.shape) 
print("Reshaped tensor:\n", y)


Original shape: torch.Size([2, 3])
Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped shape: torch.Size([6])
Reshaped tensor:
 tensor([1, 2, 3, 4, 5, 6])


In [2]:
x = torch.arange(6)   
y = x.view(2,3) 
z = x.view(3,2)

print(f"x\n {x.shape} \n {x}")
print(f"y\n {y.shape}\n {y}")
print(f"z\n {z.shape}\n {z}")

x
 torch.Size([6]) 
 tensor([0, 1, 2, 3, 4, 5])
y
 torch.Size([2, 3])
 tensor([[0, 1, 2],
        [3, 4, 5]])
z
 torch.Size([3, 2])
 tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
# Original tensor with float values
x = torch.tensor([1.7, 2.9, 3.2], dtype=torch.float32)

print(f"x\n {x.dtype} \n {x}")

# Convert to int32
y = x.to(torch.int32)

print(f"y\n {y.dtype} \n {y}")

x
 torch.float32 
 tensor([1.7000, 2.9000, 3.2000])
y
 torch.int32 
 tensor([1, 2, 3], dtype=torch.int32)


In [4]:
# x.size() is same as x.shape
x = torch.arange(3,9).reshape(2,3)
print(x)
print(x.size())
print(x.shape)

tensor([[3, 4, 5],
        [6, 7, 8]])
torch.Size([2, 3])
torch.Size([2, 3])


In [5]:
x = torch.randn(1, 3, 1, 5)
x
x.shape

torch.Size([1, 3, 1, 5])

In [6]:
x.squeeze()

tensor([[ 0.4640, -0.1361, -0.8365, -0.4143,  0.8079],
        [-0.3684,  0.0378, -1.5883,  0.2570, -1.0190],
        [ 1.5295,  0.6956, -0.0319,  0.8204, -0.9150]])

In [7]:
#Squeeze and unsqueeze to remove/add dimension
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(f"x\n  {x}")
print(f"Original shape:, {x.shape}")  

# Unsqueeze-- Add a new dimension at position 0
y = x.unsqueeze(0)
print(f"y\n  {y}")
print(f"After unsqueeze(0):, {y.shape}")  

# Squeeze-- Remove that dimension again
z = y.squeeze(0)
print(f"z\n  {z}")
print(f"After squeeze(0):, {z.shape}")    # torch.Size([2, 3])


x
  tensor([[1, 2, 3],
        [4, 5, 6]])
Original shape:, torch.Size([2, 3])
y
  tensor([[[1, 2, 3],
         [4, 5, 6]]])
After unsqueeze(0):, torch.Size([1, 2, 3])
z
  tensor([[1, 2, 3],
        [4, 5, 6]])
After squeeze(0):, torch.Size([2, 3])


In [8]:
#Transpose
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(f"Original tensor x:\n{x}")
print(f"Original shape : {x.shape}\n") 

y = x.transpose(0,1)

print(f"Transposed tensor y:\n{y}")
print(f"\nTransposed shape: {y.shape}")  

Original tensor x:
tensor([[1, 2, 3],
        [4, 5, 6]])
Original shape : torch.Size([2, 3])

Transposed tensor y:
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Transposed shape: torch.Size([3, 2])


In [9]:
#Higher Dimensions -Transpose

x = torch.randn(2, 3, 4)   


print(f"Original tensor x:\n{x}")
print(f"\nOriginal shape : {x.shape}\n")

y = x.transpose(0,1)       # swap first two dimensions

print(f"\nTransposed shape: {y.shape}") 

Original tensor x:
tensor([[[ 0.8216, -1.7861, -0.7118,  0.0075],
         [-0.2846,  2.2691,  1.0540,  0.0476],
         [ 2.3234,  0.9804, -0.2342, -0.2788]],

        [[ 0.4651, -1.7599, -2.1168, -0.7524],
         [ 0.8085, -0.7645,  0.1734, -0.6636],
         [ 1.4295,  1.0785,  0.1341,  0.3651]]])

Original shape : torch.Size([2, 3, 4])


Transposed shape: torch.Size([3, 2, 4])


In [10]:
#permute
x = torch.randn(2, 3, 4)   
y = x.permute(2, 0, 1)     # reorder dimensions

print(x.shape)  
print(y.shape)  


torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


## transpose vs permute

| Function        | Syntax                        | What it does                  | Example result          |
|-----------------|-------------------------------|-------------------------------|-------------------------|
| transpose(a,b)  | `x.transpose(dim0, dim1)`     | Swaps two dimensions only     | (2,3,4) → (3,2,4)       |
| permute(...)    | `x.permute(dims...)`          | Reorders all dimensions at once | (1,2,3,4) → (1,4,3,2) |


In [11]:
### Math & Statistics

x = torch.tensor([1.0, 2.0, 3.0, 4.0])

print(f"tensor x: {x}")
# 1. Max / Min values
print(f"\ntorch.max(x):{torch.max(x)}")   
print(f"\ntorch.min(x):{torch.min(x)}")   

# 2. Index of Max / Min
print(f"\ntorch.argmax(x):{torch.argmax(x)}")  
print(f"\ntorch.argmin(x):{torch.argmin(x)}")  

# 3. Standard Deviation
print(f"\ntorch.std(x):{torch.std(x)}")  

# 4. Variance
print(f"\ntorch.var(x):{torch.var(x)}")  

# 5. Vector Norm (magnitude)
# sqrt(1^2 + 2^2 + 3^2 + 4^2) = sqrt(30) ≈ 5.477
print(f"\ntorch.norm(x):{torch.norm(x)}")  

# 6. Clamp values to a range
y = torch.tensor([-2.0, 0.5, 1.5, 3.0])
print(f"\ntensor y: {y}")
print(f"\ntorch.clamp(y, min=0, max=1): {torch.clamp(y, min=0, max=1)}")


tensor x: tensor([1., 2., 3., 4.])

torch.max(x):4.0

torch.min(x):1.0

torch.argmax(x):3

torch.argmin(x):0

torch.std(x):1.29099440574646

torch.var(x):1.6666666269302368

torch.norm(x):5.4772257804870605

tensor y: tensor([-2.0000,  0.5000,  1.5000,  3.0000])

torch.clamp(y, min=0, max=1): tensor([0.0000, 0.5000, 1.0000, 1.0000])


In [12]:
x = torch.tensor([1.0, 2.0, 3.0])
print(f"tensor x: {x}\n")
print("Power:", torch.pow(x, 2))     
print("Square root:", torch.sqrt(x)) # tensor([1.0000, 1.4142, 1.7321])
print("Exponential:", torch.exp(x))  # e^x
print("Logarithm:", torch.log(x))    # natural log

tensor x: tensor([1., 2., 3.])

Power: tensor([1., 4., 9.])
Square root: tensor([1.0000, 1.4142, 1.7321])
Exponential: tensor([ 2.7183,  7.3891, 20.0855])
Logarithm: tensor([0.0000, 0.6931, 1.0986])


In [14]:
angles = torch.tensor([0.0, 3.1416/2, 3.1416])  # 0, π/2, π
print(f"tensor angles: {angles}\n")

print("sin:", torch.sin(angles))   # tensor([0., 1., 0.])
print("cos:", torch.cos(angles))   # tensor([1., 0., -1.])
print("tan:", torch.tan(angles))   # tensor([0., huge, 0.])

tensor angles: tensor([0.0000, 1.5708, 3.1416])

sin: tensor([ 0.0000e+00,  1.0000e+00, -7.2400e-06])
cos: tensor([ 1.0000e+00, -3.6200e-06, -1.0000e+00])
tan: tensor([ 0.0000e+00, -2.7624e+05,  7.2400e-06])
